stages:
  - install
  - test

# Job to install dependencies
install_dependencies:
  stage: install
  image: python:3.12 # Use the appropriate Python version
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
      - .pytest_cache/

# Job to run tests with pytest
run_tests:
  stage: test
  image: python:3.12 # Same Python image as above
  script:
    - pytest ./Utility --maxfail=1 --disable-warnings -q # You can modify pytest options as needed
  dependencies:
    - install_dependencies
  artifacts:
    when: always
    paths:
      - pytest_reports/
    reports:
      junit: pytest_reports/results.xml # Store test results in JUnit format for GitLab to display

# Optional: caching to speed up subsequent jobs
cache:
  paths:
    - venv/