name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv venv
          echo "VIRTUAL_ENV=$PWD/venv" >> $GITHUB_ENV
          echo "$PWD/venv/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./Utility/requirements.txt
          pip install pytest

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            venv
            .pytest_cache
          key: venv-${{ runner.os }}-${{ hashFiles('./Utility/requirements.txt') }}

      - name: Activate Virtual Environment
        run: echo "$PWD/venv/bin" >> $GITHUB_PATH

      - name: Run Pytest
        run: |
          mkdir -p pytest_reports
          pytest ./Utility --maxfail=1 --disable-warnings -q --junitxml=pytest_reports/results.xml

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: pytest_reports/results.xml
